# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  email: email@email.com
  secret_key_base: 0d07f051a995af278194b606a43ca74cb00f6e0eddd7d9063dc3e3b2d8e6d3e8970cf79e9995bdd61ffdd0ede9a20386ca265fc6630c039cd86626d315d454fb

test:
  email: email@email.com
  secret_key_base: e8892a8ff300dbf54a0d80d803537f0edef8851428bbc2fb5547b8cf85abca3b55b203f97f7cf3de36dcc4b51e100fff8287081a4c8ed4884faa0ed945b0cc5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email: email@email.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
